[package]
name = "ccfkb_unpack"
version = "1.0.0"
edition = "2024"

[dependencies]
ccfkb_lib = { workspace = true }
env_logger = { workspace = true }
serde_yml = { workspace = true }
windows = { workspace = true }
