[workspace]

members = [
    "ccfkb_pack",
    "ccfkb_unpack",
    "ccfkb_extract",
    "ccfkb_compress",
    "ccfkb_encode",
    "ccfkb_decode",
    "ccfkb_transform",
    "ccfkb_untransform",
    "ccfkb_lib"
]
